ci: adjust the workflow for pro tests

diff --git a/.github/workflows/spread.yaml b/.github/workflows/spread.yaml
--- a/.github/workflows/spread.yaml
+++ b/.github/workflows/spread.yaml
@@ -59,11 +59,18 @@ jobs:
           mv *.snap tests/spread/
           spread ${{ matrix.spread }}
 
-      - name: Run Ubuntu Pro tests
+      - name: Run Ubuntu Pro spread tests
+        env:
+          UBUNTU_PRO_TOKEN: ${{ secrets.UBUNTU_PRO_TOKEN }}
         run: |
           if [ -z "$UBUNTU_PRO_TOKEN" ]; then
-            echo "Skipping Ubuntu Pro spread tests."
-            exit
+            if [ "${{ github.event.pull_request.head.repo.full_name }}" == "canonical/craft-application" ]; then
+              echo "Error: UBUNTU_PRO_TOKEN is not set."
+              exit 1
+            else
+              echo "Warning: UBUNTU_PRO_TOKEN is not set. Skipping Pro tests"
+              exit 0
+            fi
           fi
           spread google:tests/spread/pro/
 
